import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { stableId } from "./fact-model.js";
import type { ArticleMeta, ArticleReviewAction, ArticleReviewAssessment, ArticleWritingBrief } from "./article-model.js";
import { pathExists, readJson, utcNow, writeJson } from "./util.js";
import { validateArticles } from "./article-validate.js";

function sha(text: string): string { return createHash("sha256").update(text.trim()).digest("hex"); }
async function currentPlanId(projectRoot: string): Promise<string> { const manifest = await readJson<Record<string, any>>(path.join(projectRoot, "manifest.json")); if (manifest.gates?.content_plan?.status !== "confirmed") throw new Error("article review blocked: content plan is not confirmed"); return manifest.gates.content_plan.content_plan_id; }
async function metaEntries(projectRoot: string): Promise<Array<{ path: string; meta: ArticleMeta }>> { const out: Array<{ path: string; meta: ArticleMeta }> = []; for (const channel of ["social", "media", "b2b", "site"]) { const dir = path.join(projectRoot, "articles", channel); if (!(await pathExists(dir))) continue; for (const name of await readdir(dir)) if (name.endsWith(".meta.json")) out.push({ path: path.join(dir, name), meta: await readJson<ArticleMeta>(path.join(dir, name)) }); } return out; }
async function assertBody(projectRoot: string, meta: ArticleMeta): Promise<string> { const body = (await readFile(path.join(projectRoot, meta.body_path), "utf-8")).trim(); if (sha(body) !== meta.body_sha256) throw new Error(`article ${meta.article_id} body hash mismatch; use article revise`); return body; }

export async function prepareArticleReviews(projectRoot: string): Promise<{ prepared: string[]; report_path: string }> { const planId = await currentPlanId(projectRoot); const prepared: string[] = []; for (const entry of await metaEntries(projectRoot)) { const meta = entry.meta; if (meta.content_plan_id !== planId || ["rejected", "deferred"].includes(meta.status)) continue; const body = await assertBody(projectRoot, meta); meta.review_history = meta.review_history ?? []; if (meta.status === "draft" || meta.status === "changes_requested") meta.status = "pending_review"; meta.updated_at = utcNow(); await writeJson(entry.path, meta); const brief = await readJson<ArticleWritingBrief>(path.join(projectRoot, "articles", "work", `${meta.article_id}.brief.json`)); const packet = { schema_version: 1, article_id: meta.article_id, title: meta.title, body, body_sha256: meta.body_sha256, revision: meta.current_revision, channel: meta.channel, mode: meta.mode, topic: brief.title_direction, questions: brief.questions, used_facts: brief.allowed_facts.filter((x) => meta.used_fact_ids.includes(x.fact_id)), claim_boundaries: meta.claim_boundaries, risks: meta.risks, required_checks: ["factual_accuracy", "claim_boundaries", "channel_fit", "compliance", "originality"] }; await writeJson(path.join(projectRoot, "articles", "review", `${meta.article_id}.review.json`), packet); prepared.push(meta.article_id); } await updateReviewSummary(projectRoot); await renderArticleReviewReport(projectRoot); return { prepared, report_path: "articles/review-report.md" }; }

function failed(assessment: ArticleReviewAssessment): string[] { return Object.entries(assessment.checks).filter(([, value]) => !value.pass).map(([key]) => key); }
export async function decideArticleReview(projectRoot: string, articleId: string, action: ArticleReviewAction, assessmentPath: string, reason: string): Promise<ArticleMeta> { if (!reason.trim()) throw new Error("article review decision requires a reason"); const entry = (await metaEntries(projectRoot)).find((x) => x.meta.article_id === articleId); if (!entry) throw new Error(`article not found: ${articleId}`); const meta = entry.meta; meta.review_history = meta.review_history ?? []; await assertBody(projectRoot, meta); const assessment = await readJson<ArticleReviewAssessment>(path.resolve(assessmentPath)); if (assessment.schema_version !== 1 || assessment.article_id !== articleId || assessment.body_sha256 !== meta.body_sha256) throw new Error("review assessment references the wrong article or stale body hash"); const keys = ["factual_accuracy", "claim_boundaries", "channel_fit", "compliance", "originality"] as const; for (const key of keys) if (typeof assessment.checks?.[key]?.pass !== "boolean" || !assessment.checks[key].note?.trim()) throw new Error(`review assessment is missing ${key} result/note`); const blockers = meta.risks.filter((x) => x.severity === "block"); if (action === "approve" && (failed(assessment).length || blockers.length)) throw new Error(`article approval blocked: failed checks ${failed(assessment).join(", ") || "none"}; block risks ${blockers.map((x) => x.code).join(", ") || "none"}`);
  meta.review_history.push({ review_id: stableId("article_review", articleId, meta.body_sha256, action, meta.review_history.length + 1), action, reason: reason.trim(), assessment, body_sha256: meta.body_sha256, at: utcNow() }); meta.status = action === "approve" ? "approved" : action === "request_changes" ? "changes_requested" : action === "reject" ? "rejected" : "deferred"; meta.updated_at = utcNow(); await writeJson(entry.path, meta); await updateReviewSummary(projectRoot); await renderArticleReviewReport(projectRoot); return meta; }

export async function approvedArticleInput(projectRoot: string): Promise<ArticleMeta[]> { const planId = await currentPlanId(projectRoot); const out: ArticleMeta[] = []; for (const { meta } of await metaEntries(projectRoot)) { if (meta.content_plan_id !== planId || meta.status !== "approved") continue; await assertBody(projectRoot, meta); const latest = meta.review_history?.at(-1); if (latest?.action === "approve" && latest.body_sha256 === meta.body_sha256 && !failed(latest.assessment).length && !meta.risks.some((x) => x.severity === "block")) out.push(meta); } return out; }
export async function articleReviewStatus(projectRoot: string): Promise<Record<string, number>> { const planId = await currentPlanId(projectRoot); const counts: Record<string, number> = { draft: 0, pending_review: 0, changes_requested: 0, approved: 0, rejected: 0, deferred: 0 }; for (const { meta } of await metaEntries(projectRoot)) if (meta.content_plan_id === planId) counts[meta.status] = (counts[meta.status] ?? 0) + 1; return counts; }
async function updateReviewSummary(projectRoot: string): Promise<void> { const manifestPath = path.join(projectRoot, "manifest.json"); const manifest = await readJson<Record<string, any>>(manifestPath); manifest.article_review = { content_plan_id: manifest.gates.content_plan.content_plan_id, counts: await articleReviewStatus(projectRoot), updated_at: utcNow() }; manifest.updated_at = manifest.article_review.updated_at; await writeJson(manifestPath, manifest); }
export async function renderArticleReviewReport(projectRoot: string): Promise<string> { const counts = await articleReviewStatus(projectRoot); const lines = ["# 文章人工审稿清单", "", "> approved 只表示可进入发布准备，不表示已经发布。", "", `- 待准备：${counts.draft}；待审：${counts.pending_review}；需修改：${counts.changes_requested}；已批准：${counts.approved}；已延期：${counts.deferred}；已拒绝：${counts.rejected}`, ""]; for (const { meta } of await metaEntries(projectRoot)) { const latest = meta.review_history?.at(-1); lines.push(`## ${meta.title}`, "", `- Article ID：\`${meta.article_id}\`；channel：${meta.channel}；状态：${meta.status}`, `- 正文：\`${meta.body_path}\`；v${meta.current_revision}；hash \`${meta.body_sha256.slice(0, 12)}…\``, `- 决定：${latest?.action ?? "尚未决定"}；理由：${latest?.reason ?? "—"}`, ...(latest ? Object.entries(latest.assessment.checks).map(([key, value]) => `- ${key}：${value.pass ? "通过" : "未通过"}；${value.note}`) : []), `- 下一步：${meta.status === "approved" ? "可进入发布准备" : meta.status === "changes_requested" ? "按意见 revise 后重新审稿" : "等待人工决定"}`, ""); } await mkdir(path.join(projectRoot, "articles"), { recursive: true }); await writeFile(path.join(projectRoot, "articles", "review-report.md"), lines.join("\n"), "utf-8"); return "articles/review-report.md"; }
export async function validateArticleReviews(projectRoot: string): Promise<{ ok: boolean; errors: string[]; checked: string[] }> { const base = await validateArticles(projectRoot); const errors = [...base.errors]; const checked = [...base.checked]; for (const { meta } of await metaEntries(projectRoot)) { for (const record of meta.review_history ?? []) { if (record.assessment.article_id !== meta.article_id || record.body_sha256 !== record.assessment.body_sha256) errors.push(`${meta.article_id}: broken review history reference`); } if (meta.status === "approved") { const latest = meta.review_history?.at(-1); if (latest?.action !== "approve" || latest.body_sha256 !== meta.body_sha256 || failed(latest.assessment).length) errors.push(`${meta.article_id}: approved state has no valid current approval`); } } return { ok: errors.length === 0, errors, checked }; }
