import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ArticleMeta, ArticleWritingBrief } from "./article-model.js";
import type { ContentPlan } from "./content-plan-model.js";
import { pathExists, readJson } from "./util.js";

const require = createRequire(import.meta.url); const Ajv = require("ajv/dist/2020") as typeof import("ajv/dist/2020.js").default; const addFormats = require("ajv-formats") as (ajv: InstanceType<typeof Ajv>) => void; const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
function schemaErrors(prefix: string, errors: Array<{ instancePath: string; message?: string }> | null | undefined): string[] { return (errors ?? []).map((x) => `${prefix}${x.instancePath || "/"} ${x.message ?? "invalid"}`); }
function digest(text: string): string { return createHash("sha256").update(text.trim()).digest("hex"); }

export async function validateArticles(projectRoot: string): Promise<{ ok: boolean; errors: string[]; checked: string[] }> {
  const errors: string[] = []; const checked: string[] = []; const ajv = new Ajv({ allErrors: true, strict: false }); addFormats(ajv); const briefValidator = ajv.compile(JSON.parse(await readFile(path.join(PACKAGE_ROOT, "schemas", "article-writing-brief.schema.json"), "utf-8"))); const metaValidator = ajv.compile(JSON.parse(await readFile(path.join(PACKAGE_ROOT, "schemas", "article-meta.schema.json"), "utf-8")));
  const manifest = await readJson<Record<string, any>>(path.join(projectRoot, "manifest.json")); const gate = manifest.gates?.content_plan; if (gate?.status !== "confirmed" || !gate.content_plan_id) return { ok: false, errors: ["content plan is not confirmed"], checked };
  const plan = await readJson<ContentPlan>(path.join(projectRoot, "strategy", "content-plans", `${gate.content_plan_id}.json`)); const tasks = new Map(plan.production_tasks.map((x) => [x.task_id, x])); const work = path.join(projectRoot, "articles", "work"); const briefs = new Map<string, ArticleWritingBrief>();
  if (await pathExists(work)) for (const name of await readdir(work)) if (name.endsWith(".brief.json")) { const file = path.join(work, name); const brief = await readJson<ArticleWritingBrief>(file); checked.push(path.relative(projectRoot, file)); if (!briefValidator(brief)) errors.push(...schemaErrors(`${name}:`, briefValidator.errors)); if (brief.content_plan_id !== plan.content_plan_id || brief.fact_snapshot_id !== plan.fact_snapshot_id || !tasks.has(brief.task_id)) errors.push(`${name}: stale or broken plan/task reference`); for (const image of brief.allowed_images ?? []) { if (!(await pathExists(path.join(projectRoot, image.path)))) errors.push(`${name}: allowed image missing ${image.path}`); if (image.markdown_path !== `../../${image.path}`) errors.push(`${name}: markdown_path must be ../../${image.path}`); } briefs.set(brief.article_id, brief); }
  for (const channel of ["social", "media", "b2b", "site"]) { const dir = path.join(projectRoot, "articles", channel); if (!(await pathExists(dir))) continue; for (const name of await readdir(dir)) if (name.endsWith(".meta.json")) { const file = path.join(dir, name); const meta = await readJson<ArticleMeta>(file); checked.push(path.relative(projectRoot, file)); if (!Array.isArray(meta.used_image_paths)) meta.used_image_paths = []; if (!metaValidator(meta)) errors.push(...schemaErrors(`${name}:`, metaValidator.errors)); const brief = briefs.get(meta.article_id); if (!brief || meta.content_plan_id !== plan.content_plan_id || meta.task_id !== brief.task_id || meta.channel !== brief.channel) errors.push(`${name}: missing brief or broken plan/task/channel reference`); if (brief) { const allowed = new Set(brief.allowed_facts.map((x) => x.fact_id)); for (const id of meta.used_fact_ids) if (!allowed.has(id)) errors.push(`${name}: used fact outside allowlist ${id}`); const allowedImages = new Set((brief.allowed_images ?? []).map((x) => x.path)); for (const imagePath of meta.used_image_paths ?? []) { if (!allowedImages.has(imagePath)) errors.push(`${name}: used image outside allowlist ${imagePath}`); else if (!(await pathExists(path.join(projectRoot, imagePath)))) errors.push(`${name}: used image missing ${imagePath}`); } } const body = path.join(projectRoot, meta.body_path); if (!(await pathExists(body))) errors.push(`${name}: body path is missing`); else if (digest(await readFile(body, "utf-8")) !== meta.body_sha256) errors.push(`${name}: body hash mismatch`); if (!["draft", "pending_review", "changes_requested", "approved", "rejected", "deferred"].includes(meta.status) || !meta.requires_human_review) errors.push(`${name}: invalid review lifecycle or missing human-review requirement`); } }
  const summary = manifest.article_generation; if (summary && (summary.content_plan_id !== plan.content_plan_id || summary.drafted > summary.planned)) errors.push("manifest article_generation is stale or drafted exceeds planned"); return { ok: errors.length === 0, errors, checked };
}
